name: My Workflow

on:
  pull_request:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Version Control
        uses: ale-lozano/edisa_versioning@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
